### PR TITLE
Create es build for es6 import/export 🏂

### PR DESCRIPTION
**Pull request by mesqueeb**
https://github.com/mathiasbynens/emoji-regex/issues/36

### CODE REVIEW

**Comment by mesqueeb** [comment]
I'm not sure what the travis error is...

**Comment by henrikra** [comment]
I am using this with React Native and I am able to import this library just fine like this:
`import emojiRegex from 'emoji-regex'`

So I don't really understand why this PR is needed 🤷‍♂️

**Comment by jorgecasar** [comment]
Thanks @mesqueeb!

@henrikra you can because react native transpile the code. But you couldn't do that using the only the platform. ES modules is supported in most browsers (80.79%) and you can use it without webpack, rollup or whatever.

Pika project explain very well the issue: https://www.pikapkg.com/about/

**Comment by mathiasbynens** [comment]
Fixed by #99.

**Pull request closed without merging**
